### PR TITLE
Issues 246 and 269

### PR DESCRIPTION
**Pull request by nutterb**
* Adds the `castLogical` function and tests
* Adds four vignettes
    + Getting Started: Connecting to REDCap
    + Casting Records with exportRecordsTyped
    + Missing Data Detection with exportRecordsTyped
    + Data Validation with exportRecordsTyped
* Adds several reference in help files to these vignettes
* Although #46 isn't yet implemented, the long form documentation lists the eventual casting functions for sql fields.

### CODE REVIEW

**Comment by spgarbet** [comment]
Overall love it. I need to make some edits to the precompiled-getting-started-connecting.pdf for Mac users. 

Can you upload the source Rmd files to the redcapAPI-vignette repo?

**Comment by spgarbet** [comment]
[ FAIL 0 | WARN 0 | SKIP 9 | PASS 2082 ]

**Comment by spgarbet** [comment]
── R CMD check results ───────── redcapAPI 2.8.2 ────
Duration: 31.2s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

**Comment by nutterb** [comment]
Oh, I forgot about that repo.  I have the source files in inst/vignette-source.

I assume you want them moved and deleted from this repo?

**Comment by nutterb** [comment]
Source code moved.

**Comment by spgarbet** [comment]
@nutterb I didn't realize we were including them in the inst directory (I forgot we could include external code, etc). That's probably a better idea. I can make my changes there.

**Comment by spgarbet** [comment]
Also I will probably delete the other repository to prevent any future confusion.

**Comment by spgarbet** [comment]
I noticed the FAQ does not have a corresponding vignette. Should this be there?

**Comment by spgarbet** [comment]
I think it'd be better to just have a single FAQ.

**Comment by nutterb** [comment]
Or we can do that :)

I can tie the up later today.

**Comment by spgarbet** [comment]
I've got my edits made.

**Comment by spgarbet** [comment]
I'm personally good with approving this. Do you want me to hold off for the FAQ changes? It's fine like it is for me.

**Comment by nutterb** [comment]
Nah, go ahead. Let's not hold up progress for the sake of perfection.

**Review by spgarbet — APPROVED** [review]

**Pull request merged**
