### PR TITLE
Version 14.0.3 structure change. #288

### PR DESCRIPTION
**Pull request by spgarbet**
This fixes 357 breakage for 14.0.3

### CODE REVIEW

**Review by graywh — APPROVED** [review]

**Comment by nutterb** [comment]
Bringing this up for completeness, but what are the impacts to users on older REDCap versions? I don't think there's any negative impact but I might be forgetting a nuance.

On export, I would expect previous versions to get a data frame without the new column. (Since the structure is just there to ensure a data frame is always returned)

On import, users are not required to provide all columns, so it would be fine if they didn't include the new column.

I guess maybe the risk is that users of older versions might copy the structure and try to send an api_mofukes column? Doesn't seem like a high risk to me.

Are there any other risks I'm missing?

**Comment by spgarbet** [comment]
I wondered about this myself, but really needed a quick fix. Maybe a version check and report the correct structure?

What about this?

```
api_modules=if(compareVersion(rcon$version(), "14.0.3") < 0 NULL else character(0)
```

**Comment by nutterb** [comment]
That's surprisingly compact. I like that.

**Comment by spgarbet** [comment]
I just tried to make the patch and rcon doesn't exist at the time of definition. Ugh.

**Comment by spgarbet** [comment]
There's 4 places in the code where it's used, they all have rcon. I think the easiest is to turn the structure definition into a function that is passed version. We cannot pass rcon because 2 of the usages are in the connection constructor.

**Comment by spgarbet** [comment]
What do you think of this? https://github.com/vubiostat/redcapAPI/commit/1293b3d1710f84777fe8cef03a8cf329e3b705fb

**Comment by nutterb** [comment]
Would it make sense to give the version argument of "0.0.0"? Or maybe NULL, and if it is NULL, coerce it to 0.0.0?

It might not. I'm just trying to imagine scenarios where something unexpected might happen, like calling it without a known version available.

But it may not be a realistic concern.

**Comment by spgarbet** [comment]
:shrug:

**Comment by nutterb** [comment]
Lets leave it as you have it, then. I think if it fails, it's going to be a pretty weird edge case.

I do think we probably want to put in the test suite an import where we force an older version. It should throw an error if api_modules is passed with an older version. What was the trick to forcing our own values into a connection object?

**Comment by spgarbet** [comment]
Oh, I forgot to add the test case.

**Pull request merged**
