### PR TITLE
Issue 89

### PR DESCRIPTION
**Pull request by spgarbet**
This looks worthy of release to me.

### CODE REVIEW

**Comment by nutterb** [comment]
I just added some editorial corrections to the vignette that should be included (https://github.com/vubiostat/redcapAPI-vignette/commit/2a517e3de90d692e398880ae62f3478af8cc5a9f). Also, there's a section on Reproducing this Vignette that hasn't actually be written. It has a FIXME tag on it. Perhaps we should remove that for now?

**Comment by spgarbet** [comment]
Hm. I thought I put that in. Looks like I didn't push the change up. It's broken now on my end and refuses to compile with those edits.

**Comment by spgarbet** [comment]
I pushed up the latest with edits.

**Review by nutterb — APPROVED** [review]
Looks like you got it to compile. I think it's ready to ship.

**Pull request merged**
