### PR TITLE
Iconv 290 297 314 Yet more missed cases

### PR DESCRIPTION
**Pull request by spgarbet**
This is yet another evolution in the difficulty of encoding issues. Test cases are proving HIGHLY useful in getting this working properly. 

── R CMD check results ──────────────────────── redcapAPI 2.8.4 ────
Duration: 40.4s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

── Skipped tests (9) ───────────────────────────────────────────────
• Tests to be developed for 3.0.0 release (9):
  test-151-exportRecords-ArgumentValidation.R:6:5,
  test-151-exportRecords-Functionality.R:6:5,
  test-152-exportRecordsWithDags.R:6:5,
  test-153-exportRecordsWithEvents.R:6:5,
  test-155-exportRecordsWithRepeatingInstruments.R:6:5,
  test-180-exportRecordsOffline-ArgumentValidation.R:6:5,
  test-180-exportRecordsOffline-Functionality.R:6:5,
  test-190-exportReports-ArgumentValidation.R:6:5,
  test-190-exportReports-Functionality.R:6:5

[ FAIL 0 | WARN 0 | SKIP 9 | PASS 2130 ]

### CODE REVIEW

**Comment by spgarbet** [comment]
I looked for more instances of as.character(response). I think a lot of these are safe, i.e. it's the result of a call and the server should always be returning things properly encoded. However, there are more potential errors lurking. Ugh.

Results for as.character\(response\) 

./R/createRedcapProject.R
225     as.character(response) 

./R/deleteArms.R
 92     invisible(as.character(response)) 

./R/deleteDags.R
 88     invisible(as.character(response)) 

./R/deleteEvents.R
 81     invisible(as.character(response)) 

./R/deleteRecords.R
126     invisible(as.character(response)) 

./R/deleteUserRoles.R
 89     invisible(as.character(response)) 

./R/deleteUsers.R
 89     invisible(as.character(response)) 

./R/exportSurveyLink.R
108     as.character(response) 

./R/exportSurveyQueueLink.R
 70     as.character(response) 

./R/exportSurveyReturnCode.R
108     as.character(response) 

./R/exportUserDagAssignments.R
 64     if (as.character(response) == ""){ 

./R/exportUserRoleAssignments.R
 63     if (as.character(response) == ""){ 

./R/exportUserRoles.R
 75     if (as.character(response) == ""){ 

./R/exportVersion.R
 95     as.character(response) 

./R/importArms.R
105     invisible(as.character(response)) 

./R/importDags.R
 98     invisible(as.character(response)) 

./R/importEvents.R
 99     invisible(as.character(response)) 

./R/importMappings.R
101     invisible(as.character(response)) 

./R/importMetaData.R
136     response <- as.character(response) 
148     invisible(as.character(response)) 

./R/importProjectInformation.R
 90     invisible(as.character(response)) 

./R/importRecords.R
448         as.character(response) 

./R/importRepeatingInstrumentsEvents.R
 84     invisible(as.character(response)) 

./R/importUserDagAssignments.R
107     invisible(as.character(response)) 

./R/importUserRoleAssignments.R
115     invisible(as.character(response)) 

./R/importUserRoles.R
107     invisible(as.character(response)) 

./R/importUsers.R
118     invisible(as.character(response)) 

./R/makeApiCall.R
199         message(paste0(">>>\n", as.character(response), "<<<\n")) 
257     msg_part3 <- as.character(response) 

./R/renameRecord.R
 91     invisible(as.character(response) == "1") 

./R/switchDag.R
130     success <- isTRUE(as.character(response) == "1") 
137       message(as.character(response)) 

./inst/vignette-source/redcapAPI-best-practices.Rmd
877   head(read.csv(text = as.character(response),

**Comment by spgarbet** [comment]
── Skipped tests (9) ─────────────────────────────────────────────────────
• Tests to be developed for 3.0.0 release (9):
  test-151-exportRecords-ArgumentValidation.R:6:5,
  test-151-exportRecords-Functionality.R:6:5,
  test-152-exportRecordsWithDags.R:6:5,
  test-153-exportRecordsWithEvents.R:6:5,
  test-155-exportRecordsWithRepeatingInstruments.R:6:5,
  test-180-exportRecordsOffline-ArgumentValidation.R:6:5,
  test-180-exportRecordsOffline-Functionality.R:6:5,
  test-190-exportReports-ArgumentValidation.R:6:5,
  test-190-exportReports-Functionality.R:6:5

[ FAIL 0 | WARN 0 | SKIP 9 | PASS 2130 ]

**Comment by spgarbet** [comment]
When this is approved I will push to CRAN. #318

**Review by nutterb — APPROVED** [review]
Changes are well applied and consistent. 

I agree that most of the remaining `as.character(response)` instances are low-risk. Most of them return something other than a data structure, so the as.character conversion is appropriate. 

I haven't run the test suite independently, and won't be able to until I am home tonight. But I don't see any reason to be concerned with that since your run passed all tests.

**Comment by spgarbet** [comment]
There is a a backup, that when it gets committed it triggers automated QA server runs of the test suite as well.

**Pull request merged**
