### PR TITLE
Issue 144 DAG and User Methods

### PR DESCRIPTION
**Pull request by nutterb**
Adds
* importUsers
* deleteUsers
* exportUserRoles
* importUserRoles
* deleteUserRoles
* exportUserRoleAssignment
* importUserRoleAssignment
* exportDags
* importDags
* deleteDags
* exportUserDagAssignment
* importUserDagAssignment
* switchDags

Tests are provided for all of the new methods.

Note: So as to not disrupt the current test project, this PR runs tests against the "Testing redcapAPI" project. We will want to change this to the primary testing project before we merge this into main.

With the new methods, it becomes possible to do additional testing for data access groups and user roles.  This required adding an expendable user. This is added as a constant in `helper-00-REDCapQACredentials.R` for the expendable user name.  I've also added a constant for the report number (this was previously a system variable, but I didn't understand how that was working so we may need to restore that if we want to continue that strategy). 

Importantly, the additional data access group testing led me to explore building the testing suite incrementally. See `test/TestingStrategy.md` for details on how the test are ordered.  Essentially, functions that don't require the API are tested first, then structural methods, then records and reports, followed by post-processing. The advantage to this is a more efficient testing suite; I have incorporated all of the existing tests, expanding from 1729 to 1792 tests while reducing the time to run the tests to less than half.

When this is completed, the only methods not supported by `redcapAPI` will be

* renameRecord
* exportSurveyLink
* exportSurveyQueueLink
* exportSurveyReturnCode
* createProject
* exportProjectXml

### CODE REVIEW

**Comment by spgarbet** [comment]
This change set will break all the automation we've put in place. The automation environment may set system variables. 

## Prime Example: 

[tests/testthat/test-13-reports-functionality.R](https://github.com/vubiostat/redcapAPI/blob/3ffc01a58c03c7c03dd249fe7ccc95b7a6197001/tests/testthat/test-13-reports-functionality.R#L4)

`report_ids = as.numeric(strsplit(Sys.getenv('REPORT_IDS', '357209,362756'), ',')[[1]])`

This pulls from the system the targeted report ids for the test.

In this change set it's become:

https://github.com/vubiostat/redcapAPI/blob/issue-144-dag-user-methods/tests/testthat/helper-00-REDCapQACredentials.R#L33C1-L33C28

```
EXPORT_REPORTS_ID <- 375181 # tests/testthat/helper-00-REDCapQACredentials.R

...

report_ids = as.numeric(strsplit(Sys.getenv('REPORT_IDS', '357209,362756'), ',')[[1]])

report_ids <- EXPORT_REPORTS_ID

```

This overwrites anything coming from the environment. 

Recommendation is to move system dependent testing variables into it's own helper file that precedes the unlock file. 

```
# These things are definable via system variables
EXPENDABLE_USER   <- Sys.getenv('EXPENDABLE_USER', "bstat_api_user")
EXPORT_REPORTS_ID <-  as.numeric(strsplit(Sys.getenv('REPORT_IDS', '375181'), ',')[[1]])
RUN_DAG_TESTS     <- Sys.getenv('RUN_DAG_TESTS', TRUE)
```

Then have the credential file create or not the "rcon" variable that controls whether dag tests are run. 

## Question

```
unlockREDCap(
  c(rcon_orig ="TestRedcapAPI", ## Change to rcon when satisfied with testing
    rcon = "DataTypes"),        ## Delete this to change to primary project
  url=url, keyring='API_KEYs', 
  envir=globalenv())
```

Are we targeting switching out the database to one with this expendable user? Or is it going to skip DAG tests if it doesn't have the user?

**Comment by spgarbet** [comment]
In addition we are looking at creating a dummy test user. That's rattling around through the usual channels starting about a week ago.

**Comment by spgarbet** [comment]
We do have a test user configured for this.

**Comment by nutterb** [comment]
It just sunk in for me that `Sys.getenv` is behaving the same as `getOption` where the second argument is what is returned IF there isn't already a system variable defined. This makes a lot more sense now.

Which makes me think what we want is 

```
EXPENDABLE_USER   <- Sys.getenv('EXPENDABLE_USER', "bstat_api_user")
EXPORT_REPORTS_ID <- as.numeric(strsplit(Sys.getenv('REPORT_IDS', '375181'), ',')[[1]])

RUN_USER_TESTS <- ## perform a check to see if EXPENDABLE_USER can be added to the project
RUN_REPORTS_TEST <- ## perform a check to see if these reports exist in the project
```

These would be placed in a helper file AFTER the credentials, since we will need the connection object to check against the project. These can be used as skip conditions in the testing, allowing the test suite to function out of the box when it leaves our REDCap environment.


> Are we targeting switching out the database to one with this expendable user? Or is it going to skip DAG tests if it doesn't have the user?

This was not my intention. My intention was to switch the test suite to the TestRedcapAPI project, but only after persuading the rest of the collaborators that the test suite is adequate and functions according to your needs. I didn't want to switch it over just yet for fear of creating clashes with other testing/development that may be occurring.

**Comment by spgarbet** [comment]
Okay, understanding better. Then it can come after credentials.

**Comment by nutterb** [comment]
Added a helper file for system variables with

```
# These things are definable via system variables

EXPENDABLE_USER   <- Sys.getenv('EXPENDABLE_USER', "bstat_api_user")
EXPORT_REPORTS_ID <- as.numeric(strsplit(Sys.getenv('REPORT_IDS', '375181'), ',')[[1]])


# Determine if tests can be run based on the system variables
RUN_USER_TESTS <- length(EXPENDABLE_USER) == 1
RUN_REPORTS_TEST <- TRUE

tryCatch( {exportReportsTyped(conns$rcon, report_id = EXPORT_REPORTS_ID) }, 
          error = function(cond) RUN_REPORTS_TEST <<- FALSE)
```

Skip conditions now run off of `RUN_USER_TESTS` and `RUN_REPORTS_TEST`

**Review by spgarbet — COMMENTED** [review]
This looks great. I'm ready to approve, but I need to coordinate the merge to main with the upstream automation.

**Comment by spgarbet** [comment]
win builder devel check:

Dear package maintainer,

this notification has been generated automatically.
Your package redcapAPI_2.8.0.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwin-builder.r-project.org%2F6unxA7e4bK5L&data=05%7C01%7Cshawn.garbett%40vumc.org%7Cf3ee9e2da21a4d90ba3f08db9e732cea%7Cef57503014244ed8b83c12c533d879ab%7C0%7C0%7C638277989743501820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=k2Gz3Um1cCZ8yyPUkH0CsATso0xNjrcIvoLTgACaX%2F8%3D&reserved=0
The files will be removed after roughly 72 hours.
Installation time in seconds: 7
Check time in seconds: 84
Status: OK
R Under development (unstable) (2023-08-15 r84956 ucrt)

**Comment by spgarbet** [comment]
I get one failure cutting the tests over: 

```
Failure (test-056-redcapError.R:51:5): Return the error if it isn't one of the handled errors
`redcapError(response_list)` threw an error with unexpected message.
Expected match: "701: my error"
Actual message: "a character vector argument expected"
Backtrace:
     ▆
  1. ├─testthat::expect_error(redcapError(response_list), "701: my error") at test-056-redcapError.R:51:4
  2. │ └─testthat:::quasi_capture(...)
  3. │   ├─testthat (local) .capture(...)
  4. │   │ └─base::withCallingHandlers(...)
  5. │   └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
  6. └─redcapAPI:::redcapError(response_list)
  7.   ├─base::as.character(x) at redcapAPI/R/redcapError.R:50:2
  8.   └─httr:::as.character.response(x) at redcapAPI/R/redcapError.R:50:2
  9.     └─httr::content(x, "text")
 10.       ├─type %||% x$headers[["Content-Type"]] %||% ...
 11.       └─mime::guess_type(x$url, empty = "application/octet-stream")
 12.         └─base::basename(file)

[ FAIL 1 | WARN 0 | SKIP 11 | PASS 1792 ]
```

**Comment by nutterb** [comment]
What is the version number for the `httr` package on that system?

**Comment by spgarbet** [comment]
Looking at the code for `redcapError`, this line give me pause:

```
 if (error_message %in% handle && error_handling == "null") {
```

Should this be `is.null(error_handling)` ?

**Comment by spgarbet** [comment]
> What is the version number for the httr package on that system?

httr_1.4.5

**Comment by nutterb** [comment]
> Looking at the code for `redcapError`, this line gives me pause (🐾) :
> 
> ```
>  if (error_message %in% handle && error_handling == "null") {
> ```
> 
> Should this be `is.null(error_handling)` ?

No. This gets passed from the `error_handling` argument of the various API functions.  See `exportArms` for example (https://github.com/vubiostat/redcapAPI/blob/main/R/exportArms.R#L85-L88)
```
error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"),
                                        .var.name = "error_handling",
                                        add = coll)
```

**Comment by spgarbet** [comment]
trace:

```
> as.character(response_list)
Error in basename(file) : a character vector argument expected
> traceback()
6: basename(file)
5: mime::guess_type(x$url, empty = "application/octet-stream")
4: type %||% x$headers[["Content-Type"]] %||% mime::guess_type(x$url, 
       empty = "application/octet-stream")
3: content(x, "text")
2: as.character.response(response_list)
1: as.character(response_list)
```

**Comment by nutterb** [comment]
I think it's probably something upstream of httr is being a bit more strict in reading the `response` object.  Perhaps the `mime` package.  Whatever it is, it doesn't like my cheap attempt to make a response object.

I've just pushed a commit that modifies a response object that was destined to fail. I hope this works better.

**Comment by spgarbet** [comment]
That last patch looks good. I don't think this would ever be an issue for an end user. I'm working on coordinating the build environment upgrades. When I get that lined up I'll approve/merge.

**Review by spgarbet — APPROVED** [review]
I think we're good. I like that I pointed at an older database and it auto migrated.

**Comment by nutterb** [comment]
Do we want to change the credential file from https://github.com/vubiostat/redcapAPI/blob/main/tests/testthat/helper-00-REDCapQACredentials.R#L24C1-L28C21

```
conns <- unlockREDCap(
  c(rcon_orig ="TestRedcapAPI", ## Change to rcon when satisfied with testing
    rcon = "DataTypes"),        ## Delete this to change to primary project
  url=url, keyring='API_KEYs', 
  envir=globalenv())
```
 to 

```
conns <- unlockREDCap(
  c(rcon ="TestRedcapAPI"),
  url=url, keyring='API_KEYs', 
  envir=globalenv())
```

**Pull request merged**
