### PR TITLE
Issue 244 invalid report links

### PR DESCRIPTION
**Pull request by nutterb**
* Adds constructLinkToRedcapForm function. This will issue a warning when we can determine that the link will not work, and return an NA instead of a link. For offline connections, it is possible to not know if the link is complete. A warning is issued in those cases.
* Uses this function in generating the Invalid Data Frame. Modifies the format.invalid function to format the link in Markdown.
* Updates the offline connection test files. These files haven't been updated in some time. The files now reflect the state of the testing database at the completion of the test suite.

### CODE REVIEW

**Comment by spgarbet** [comment]
── R CMD check results ────────────────────────────────── redcapAPI 2.8.1 ────
Duration: 20.2s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

**Comment by spgarbet** [comment]
Just got done playing with this feature and it works really well. Love it.

**Comment by spgarbet** [comment]
── Failed tests ──────────────────────────────────────────────────────────────
Error (test-205-exportTypedRecords-offline-Functionality.R:99:5): Invalid data is reported, links generated with event IDs provided
Error in `eval(code, test_env)`: object 'rcon_off' not found

Error (test-205-exportTypedRecords-offline-Functionality.R:128:5): Invalid data is reported, links not generated without the version number
Error in `eval(code, test_env)`: object 'Evt' not found
Backtrace:
     ▆
  1. ├─testthat::expect_warning(...) at test-205-exportTypedRecords-offline-Functionality.R:128:4
  2. │ └─testthat:::quasi_capture(...)
  3. │   ├─testthat (local) .capture(...)
  4. │   │ └─base::withCallingHandlers(...)
  5. │   └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
  6. └─redcapAPI::offlineConnection(...)
  7.   ├─checkmate::assert(...) at redcapAPI/R/redcapConnection.R:439:2
  8.   │ └─base::eval(dots[[i]], envir = env)
  9.   │   └─base::eval(dots[[i]], envir = env)
 10.   └─checkmate::check_character(x = events, len = 1, null.ok = TRUE)
 11.     └─... %and% ...
 12.       └─base::isTRUE(lhs)

[ FAIL 2 | WARN 0 | SKIP 9 | PASS 2011 ]

**Comment by nutterb** [comment]
Oops. Those tests weren't fully self contained.  Should be fixed now.

**Comment by spgarbet** [comment]
══ Results ══════════════════════════════════════════════════════
Duration: 1142.3 s

── Skipped tests (9) ────────────────────────────────────────────
• Tests to be developed for 3.0.0 release (9):
  test-151-exportRecords-ArgumentValidation.R:6:5,
  test-151-exportRecords-Functionality.R:6:5,
  test-152-exportRecordsWithDags.R:6:5,
  test-153-exportRecordsWithEvents.R:6:5,
  test-155-exportRecordsWithRepeatingInstruments.R:6:5,
  test-180-exportRecordsOffline-ArgumentValidation.R:6:5,
  test-180-exportRecordsOffline-Functionality.R:6:5,
  test-190-exportReports-ArgumentValidation.R:6:5,
  test-190-exportReports-Functionality.R:6:5

[ FAIL 0 | WARN 0 | SKIP 9 | PASS 2016 ]

**Pull request merged**
