### PR TITLE
Issue 246 Separate FAQ Document

### PR DESCRIPTION
**Pull request by nutterb**
In addition to separating all FAQ's into a single document, additional documentation around data validation is provided. This includes language describing project level missing value codes.

### CODE REVIEW

**Comment by spgarbet** [comment]
── R CMD check results ─ redcapAPI 2.8.3 ────
Duration: 32.5s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

**Comment by spgarbet** [comment]
NOTE: This makes no sense, but there's been weird failures all morning.

── Failed tests ────────────────────────────────────────────────────
Failure (test-801-changedRecords.R:22:5): Returns records known to change in prior tests
all(recs %in% x$deleted) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

[ FAIL 1 | WARN 0 | SKIP 12 | PASS 2109 ]

**Comment by spgarbet** [comment]
Worked on second pass. Looks like log retrieval is unstable, probably due to new caching layer.

**Review by spgarbet — APPROVED** [review]

**Comment by nutterb** [comment]
I had that pop up when I was getting ready to submit, but it went away when I ran the suite again, so I figured it was server weirdness. 

Seeing it pop up for you actually made me go look at the file. The records we are pulling up are only for the past 24 hours. 

```
    x <- changedRecords(rcon, beginTime=as.POSIXct(Sys.time()-86400))
```

Perhaps this is happening because it isn't seeing deleted record events within the search window?  I would have thought there would be some because we purge the project at the start of testing. 

In any case, I think it's something wonky in how we've designed the tests, but not related to this issue.


......and now I see you seem to have figured that out too.  :)

**Comment by spgarbet** [comment]
With 10.0.2 they put in a caching layer. I think it's caching an old call and not updating in time. The records are definitely deleted by that point. For us, it's good we wrote that before they turned on caching.

**Comment by nutterb** [comment]
It's starting to feel like I should just start blaming every new problem on caching :)

**Pull request merged**
