### PR TITLE
Set empty strings in meta data to NA #345

### PR DESCRIPTION
**Pull request by spgarbet**

### CODE REVIEW

**Comment by nutterb** [comment]
> Don't know if this is a good or bad idea.

It should be fine. Eventually NAs are forced to "" when writing the csv for import. I'm not sure where the error is occurring (has to be one of our validations). But I'm struggling to imagine a place where this would shoot us in the foot

**Comment by obregos** [comment]
Tests to be developed for 3.0.0 release (9)

[ FAIL 11 | WARN 10 | SKIP 9 | PASS 1082 ]

```
Failure (test-107-eventsMethods-Functionality.R:59:5): Import, Export, and Deletion of Arms Execute Successfully
Check on 'exportEvents(rcon)' failed: Must have exactly 5 cols, but has 8 cols
Backtrace:
 1. checkmate::expect_data_frame(exportEvents(rcon), ncols = 5, nrows = 3)
      at test-107-eventsMethods-Functionality.R:59:4
 2. checkmate::makeExpectation(x, res, info, label)

Failure (test-107-eventsMethods-Functionality.R:112:5): Test the override argument in importEvents
Check on 'exportEvents(rcon)' failed: Must have exactly 5 cols, but has 8 cols
Backtrace:
 1. checkmate::expect_data_frame(exportEvents(rcon), ncols = 5, nrows = 3)
      at test-107-eventsMethods-Functionality.R:112:4
 2. checkmate::makeExpectation(x, res, info, label)

Failure (test-107-eventsMethods-Functionality.R:167:5): Confirm that we can add additional events and delete specific events
Check on 'exportEvents(rcon)' failed: Must have exactly 5 cols, but has 8 cols
Backtrace:
 1. checkmate::expect_data_frame(exportEvents(rcon), ncols = 5, nrows = 3)
      at test-107-eventsMethods-Functionality.R:167:4
 2. checkmate::makeExpectation(x, res, info, label)

Failure (test-107-eventsMethods-Functionality.R:181:5): Confirm that we can add additional events and delete specific events
Check on 'exportEvents(rcon)' failed: Must have exactly 5 cols, but has 8 cols
Backtrace:
 1. checkmate::expect_data_frame(exportEvents(rcon), ncols = 5, nrows = 5)
      at test-107-eventsMethods-Functionality.R:181:4
 2. checkmate::makeExpectation(x, res, info, label)

Failure (test-107-eventsMethods-Functionality.R:194:5): Confirm that we can add additional events and delete specific events
Check on 'exportEvents(rcon)' failed: Must have exactly 5 cols, but has 8 cols
Backtrace:
 1. checkmate::expect_data_frame(exportEvents(rcon), nrows = 3, ncols = 5)
      at test-107-eventsMethods-Functionality.R:194:4
 2. checkmate::makeExpectation(x, res, info, label)

Error (test-200-exportTypedRecords-Functionality.R:379:5): Casting Zero-coded check values works correctly
Error in `factor(unname(c("", the_level)[(x_checked) + 1]), levels = c("", 
    the_level), labels = c("", the_label))`: invalid 'labels'; length 2 should be 1 or 1
Backtrace:
  1. testthat::expect_warning(...)
       at test-200-exportTypedRecords-Functionality.R:379:4
  7. redcapAPI:::exportRecordsTyped.redcapApiConnection(...)
       at redcapAPI/R/exportRecordsTyped.R:6:2
  8. redcapAPI:::.castRecords(...)
       at redcapAPI/R/exportRecordsTyped.R:233:2
  9. redcapAPI:::.castRecords_castRecords(...)
       at redcapAPI/R/fieldCastingFunctions.R:577:2
 10. redcapAPI (local) typecast(x, field_name = field_names[i], coding = codings[[i]])
       at redcapAPI/R/fieldCastingFunctions.R:864:6
 11. base::factor(...)
       at redcapAPI/R/fieldValidationAndCasting.R:365:2

Error (test-200-exportTypedRecords-Functionality.R:517:5): Batching behaves correctly when records have data in multiple events
Error in `devtools::test()`: 1 assertions failed:
 * Variable 'data$form': Must be a subset of {'record_id','multiple_choice'}, but has additional elements
 * {'text_fields','dates_and_times','numbers','slider_fields','files_notes_descriptions','calculated_fields'}.
Backtrace:
 1. redcapAPI::importMappings(rcon, data = NewMapping)
      at test-200-exportTypedRecords-Functionality.R:517:4
 2. redcapAPI:::importMappings.redcapApiConnection(rcon, data = NewMapping)
      at redcapAPI/R/importMappings.R:9:2
 3. checkmate::reportAssertions(coll)
      at redcapAPI/R/importMappings.R:74:2

Failure (test-202-exportTypedRecords-withEvents.R:36:5): Event names can be labelled or raw
levels(Records$redcap_event_name) not equal to c("Event 1 (Arm 1: Arm 1)", "Event 2 (Arm 2: Arm2)").
Lengths differ: 3 is not 2

Error (test-202-exportTypedRecords-withEvents.R:59:3): forms with mapping are filtered
Error in `devtools::test()`: 1 assertions failed:
 * Variable 'forms': Must be a subset of {'record_id','multiple_choice'}, but has additional elements {'numbers'}.
Backtrace:
 1. testthat::expect_equal(...)
      at test-202-exportTypedRecords-withEvents.R:59:2
 6. redcapAPI:::exportRecordsTyped.redcapApiConnection(...)
      at redcapAPI/R/exportRecordsTyped.R:6:2
 7. checkmate::reportAssertions(coll)
      at redcapAPI/R/exportRecordsTyped.R:158:2

Error (test-205-exportTypedRecords-offline-Functionality.R:101:5): Invalid data is reported, links generated with event IDs provided
Error in ``$<-.data.frame`(`*tmp*`, event_id, value = c(479625L, 479627L, 
479626L))`: replacement has 3 rows, data has 2
Backtrace:
 1. base::`$<-`(`*tmp*`, event_id, value = `<int>`)
      at test-205-exportTypedRecords-offline-Functionality.R:101:4
 2. base::`$<-.data.frame`(`*tmp*`, event_id, value = `<int>`)
      at test-205-exportTypedRecords-offline-Functionality.R:101:4

Error (test-205-exportTypedRecords-offline-Functionality.R:131:5): Invalid data is reported, links not generated without the version number
Error in ``$<-.data.frame`(`*tmp*`, event_id, value = c(479625L, 479627L, 
479626L))`: replacement has 3 rows, data has 2
Backtrace:
 1. base::`$<-`(`*tmp*`, event_id, value = `<int>`)
      at test-205-exportTypedRecords-offline-Functionality.R:131:4
 2. base::`$<-.data.frame`(`*tmp*`, event_id, value = `<int>`)
      at test-205-exportTypedRecords-offline-Functionality.R:131:4
```

**Comment by spgarbet** [comment]
I think you've just had a midair collision on use of the REDCap project. I reran and got the following:

══ Results ═════════════════════════════════════════════════════════════════════════════════
Duration: 824.9 s

── Skipped tests (9) ───────────────────────────────────────────────────────────────────────
• Tests to be developed for 3.0.0 release (9):
  test-151-exportRecords-ArgumentValidation.R:6:5,
  test-151-exportRecords-Functionality.R:6:5, test-152-exportRecordsWithDags.R:6:5,
  test-153-exportRecordsWithEvents.R:6:5,
  test-155-exportRecordsWithRepeatingInstruments.R:6:5,
  test-180-exportRecordsOffline-ArgumentValidation.R:6:5,
  test-180-exportRecordsOffline-Functionality.R:6:5,
  test-190-exportReports-ArgumentValidation.R:6:5,
  test-190-exportReports-Functionality.R:6:5

[ FAIL 0 | WARN 0 | SKIP 9 | PASS 2161 ]

**Comment by spgarbet** [comment]
── R CMD check results ────────────────────────── redcapAPI 2.8.5 ────
Duration: 54.2s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

**Comment by obregos** [comment]
[ FAIL 1 | WARN 0 | SKIP 9 | PASS 2159 ] 
Error (test-240-exportTypedReports-Functionality.R:63:5): exportReportsTyped responds to drop_fields
Error in `devtools::test()`: 1 assertions failed:
 * Variable 'drop_fields': Must be a subset of
 
 Pulled most recent patch and got no fails:
 [ FAIL 0 | WARN 0 | SKIP 12 | PASS 2157 ]

**Review by obregos — APPROVED** [review]

**Pull request merged**
