### PR TITLE
Resolve issue of all unchecked checkboxes being returned as NA values

### PR DESCRIPTION
**Pull request by nutterb**
* Immediately after receiving the raw data from the API, replace missing value in checkboxes with 0.
* The conversion to zero is handled in a distinct function, allowing tests to be performed without having to make a call to the API.

Noting also that it is not quite agreed upon that this is an appropriate solution. Criticisms of the approach are encouraged.

### CODE REVIEW

**Comment by spgarbet** [comment]
I have some trepidation about this patch (as you anticipated). 1) Shouldn't the raw be set to "0" and not 0? 2) Wouldn't this trigger  filterEmptyRows to always be TRUE for any form containing a checkbox? `is_all_missing <- apply(is.na(data[other_fields]), 1, all)`.

**Comment by nutterb** [comment]
1. Yes it should 
2. I hadn't quite processed the ``form_complete`  idea before I submitted this. 

If I understand correctly, you think this should only apply to records where the user has marked the form complete. That way, if there is an instrument that hasn't been filled out yet (perhaps it is for a follow up visit), the data for that form would get dropped in the export. We don't need it if the form isn't completed yet. 

If my understanding is correct, I can see it both ways. It has a certain logic. User hasn't declared the data ready, check boxes remain zero.

On the other hand, there is no other field type that behaves this way. If we were talking about drop downs, we wouldn't argue that the value of a drop-down field should be considered missing because the form isn't marked complete, would we? 

If I've not understood correctly, we might need to draft up some scenarios in data tomorrow

**Comment by spgarbet** [comment]
Yep. Your questions demonstrate an understanding of my concerns. I think that no other field will behave this way, but there is no way to really know for zero coded fields outside of form_complete. It's a bad problem with no good solution outside of that. I think the warnings / documentation should reflect these issues. The flag to turn them off these warnings documentation should be very clear about the problems.

**Comment by spgarbet** [comment]
Oh, I see the case of "form_complete" is FALSE, but values on the form have been entered. Ugh. It should be if anything on the defined form is present, then it inserts the "0". Ugly. This is a horrible no good problem.

**Comment by spgarbet** [comment]
Another idea: Open a support ticket with REDCap and ask them to fix this.

**Comment by nutterb** [comment]
Just burst out laughing 😂

Love this idea.

**Comment by nutterb** [comment]
Turns out we could just move the filterEmptyRows call to after casting the data. The only side effect I can think of is if a record gets filtered out because it had data that failed validation. I think I'm willling to take that chance. 

Benefits: no new methods, no new code, no new tests.   All tests are still passing. 

I said I would add something to the documentation.  But I can't think of where to put it. And part of me thinks it isn't that necessary.  This is now behaving the same way the UI exports would. I'm not sure what we could say that wouldn't sound weird.

I'm willing to draft language for this if anyone thinks there's a good place to include it.

**Comment by spgarbet** [comment]
After phone conversations, I think this is the best approach we can offer.

**Comment by spgarbet** [comment]
── R CMD check results ──────────────────────── redcapAPI 2.8.3 ────
Duration: 31.5s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

**Comment by spgarbet** [comment]
── Skipped tests (9) ───────────────────────────────────────────────────────────────────
• Tests to be developed for 3.0.0 release (9):
  test-151-exportRecords-ArgumentValidation.R:6:5,
  test-151-exportRecords-Functionality.R:6:5, test-152-exportRecordsWithDags.R:6:5,
  test-153-exportRecordsWithEvents.R:6:5,
  test-155-exportRecordsWithRepeatingInstruments.R:6:5,
  test-180-exportRecordsOffline-ArgumentValidation.R:6:5,
  test-180-exportRecordsOffline-Functionality.R:6:5,
  test-190-exportReports-ArgumentValidation.R:6:5,
  test-190-exportReports-Functionality.R:6:5

[ FAIL 0 | WARN 0 | SKIP 9 | PASS 2119 ]

**Comment by spgarbet** [comment]
I just put a notice in NEWS. I think that is sufficient.

**Review by spgarbet — APPROVED** [review]

**Pull request merged**
