### PR TITLE
Issue 285 codebook improvement

### PR DESCRIPTION
**Pull request by nutterb**
Adds *_form_complete fields, system fields, and field labels to the output.

### CODE REVIEW

**Comment by couthcommander** [comment]
I've partially reviewed and have a couple of questions.

I see three "System Fields" but expected four. Missing is "redcap_repeat_instance".

More complicated is field_labels for checkboxes. This is what the codebook produces for the test instance (I've reordered).
```
                  field_name                                field_label       form_name
72         checkbox_test___x                           Checkbox Example multiple_choice
64         checkbox_test___y                           Checkbox Example multiple_choice
66         checkbox_test___z                           Checkbox Example multiple_choice
70       checkbox_test____90                           Checkbox Example multiple_choice
68       checkbox_test____98                           Checkbox Example multiple_choice
62       checkbox_test____99                           Checkbox Example multiple_choice
106      prereq_checkbox___1                Pre-requisite as a checkbox branching_logic
118      prereq_checkbox___2                Pre-requisite as a checkbox branching_logic
108    prereq_checkbox___abc                Pre-requisite as a checkbox branching_logic
116      prereq_checkbox___4                Pre-requisite as a checkbox branching_logic
114    prereq_checkbox____90                Pre-requisite as a checkbox branching_logic
112    prereq_checkbox____98                Pre-requisite as a checkbox branching_logic
110    prereq_checkbox____99                Pre-requisite as a checkbox branching_logic
135   no_prereq_checkbox___1                  No pre-requisite checkbox branching_logic
125   no_prereq_checkbox___2                  No pre-requisite checkbox branching_logic
127   no_prereq_checkbox___3                  No pre-requisite checkbox branching_logic
131 no_prereq_checkbox____90                  No pre-requisite checkbox branching_logic
129 no_prereq_checkbox____98                  No pre-requisite checkbox branching_logic
133 no_prereq_checkbox____99                  No pre-requisite checkbox branching_logic
```
Based on this metadata
```
         form_name         field_name                 field_label                                                    select_choices_or_calculations
28 multiple_choice      checkbox_test            Checkbox Example                                              x, Guitar | y, Ukulele | z, Mandolin
43 branching_logic    prereq_checkbox Pre-requisite as a checkbox 1, Checkbox1 | 2, Checkbox2 | ABC, CheckboxABC | 4, Do not use in branching logic
48 branching_logic no_prereq_checkbox   No pre-requisite checkbox                                              1, Pretzel | 2, Chocolate | 3, Fruit
```
I would have expected this output:
```
               field_name                                                        field_label       form_name
1       checkbox_test___x                                   Checkbox Example (choice=Guitar) multiple_choice
2       checkbox_test___y                                  Checkbox Example (choice=Ukulele) multiple_choice
3       checkbox_test___z                                 Checkbox Example (choice=Mandolin) multiple_choice
4     prereq_checkbox___1                     Pre-requisite as a checkbox (choice=Checkbox1) branching_logic
5     prereq_checkbox___2                     Pre-requisite as a checkbox (choice=Checkbox2) branching_logic
6   prereq_checkbox___abc                   Pre-requisite as a checkbox (choice=CheckboxABC) branching_logic
7     prereq_checkbox___4 Pre-requisite as a checkbox (choice=Do not use in branching logic) branching_logic
8  no_prereq_checkbox___1                         No pre-requisite checkbox (choice=Pretzel) branching_logic
9  no_prereq_checkbox___2                       No pre-requisite checkbox (choice=Chocolate) branching_logic
10 no_prereq_checkbox___3                           No pre-requisite checkbox (choice=Fruit) branching_logic
```
I prefer my more descriptive labels, so
1. can that done?
2. how to handle 90/98/99, for which there is not metadata?

**Comment by nutterb** [comment]
> 1. can/should that done?

Yeah, probably.  I'll get that worked in and resubmit

> 2. how to handle 90/98/99, for which there is not metadata?

This one is a bit tricky.  I believe you're referring to what I've termed "Project Level Missing Value Codes" in [this vignette](https://github.com/vubiostat/redcapAPI/blob/issue-246-casting-longform-doc/vignettes/precompiled-missing-data-detection.pdf), pages 5-7 (under review in #295). unfortunately, the API does not give us access to the codes, and our current solution is to enter them manually. I wonder if we need to devise a way to permit the user to enter these values.  Would you expect these all to be repeated under each variable?

**Comment by couthcommander** [comment]
Exactly - yes, I would expect this to be repeated.

If not in "select_choices_or_calculations" metadata, I would set field_label to choice=NA.

```
assembleCodebook(rcon)
1       checkbox_test____90                            Checkbox Example (choice=NA) multiple_choice
2       checkbox_test____98                            Checkbox Example (choice=NA) multiple_choice
3       checkbox_test____99                            Checkbox Example (choice=NA) multiple_choice
```
Argument "customMissing" (or whatever) could provide these.
```
assembleCodebook(rcon, customMissing = 
  list(90 = "Below limit of quantitation", 98 = "Question not asked", 99 = "Could not contact")
)
1       checkbox_test____90                            Checkbox Example (choice=Below limit of quantitation) multiple_choice
2       checkbox_test____98                            Checkbox Example (choice=Question not asked) multiple_choice
3       checkbox_test____99                            Checkbox Example (choice=Could not contact) multiple_choice
```

**Comment by nutterb** [comment]
I'm going to close this for now.  If we fix the field labels at a lower level, they can be consistent across this and `exportRecordsTyped`, which I think is probably better. 

With the missing value codes, I think we should probably consider providing the user a way to enter the missing value codes, very much like was proposed here. What's a little more bloat on the rcon object?  

But at heart, I think both of those will be better served if they are addressed as separate, focused efforts that get proper review, rather than cramming them into this request.  Once both are implemented, it should be fairly easy to finish this off.

**Comment by nutterb** [comment]
@couthcommander I still need to add tests for this, but wondered if you might give this a run through before I invest time in the testing. 

The field labels should be present as desired.  Project-level missing data codes are added to each field.

I was not very judicious with the missing data codes. They get added to every field except system fields and record ID fields (both the primary and secondary ID, if one exists).  this means they are also added to numeric fields, text fields, and even_form_complete fields, which I'm not sure is relevant. There may need to be some refinements on those.

**Comment by nutterb** [comment]
Just confirmed that form_complete fields are not subject to missing data codes. I've removed those codes from those fields.

**Comment by spgarbet** [comment]
── R CMD check results ──────────────────────────────────────────── redcapAPI 2.8.3 ────
Duration: 36.6s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

**Comment by spgarbet** [comment]
══ Results ═════════════════════════════════════════════════════════════════════════════
Duration: 691.1 s

── Skipped tests (9) ───────────────────────────────────────────────────────────────────
• Tests to be developed for 3.0.0 release (9):
  test-151-exportRecords-ArgumentValidation.R:6:5,
  test-151-exportRecords-Functionality.R:6:5, test-152-exportRecordsWithDags.R:6:5,
  test-153-exportRecordsWithEvents.R:6:5,
  test-155-exportRecordsWithRepeatingInstruments.R:6:5,
  test-180-exportRecordsOffline-ArgumentValidation.R:6:5,
  test-180-exportRecordsOffline-Functionality.R:6:5,
  test-190-exportReports-ArgumentValidation.R:6:5,
  test-190-exportReports-Functionality.R:6:5

[ FAIL 0 | WARN 0 | SKIP 9 | PASS 2120 ]

**Review by spgarbet — APPROVED** [review]

**Comment by couthcommander** [comment]
This is still missing the "redcap_repeat_instance" system field

**Pull request merged**
