### PR TITLE
set default dag arg to false

### PR DESCRIPTION
**Pull request by obregos**
Issue #365 
Set default dag argument to FALSE

### CODE REVIEW

**Comment by spgarbet** [comment]
Update the documentation to reflect how it doesn't work now without the permission. 
https://github.com/vubiostat/redcapAPI/blob/main/R/docsRecordsTypedMethods.R#L30-L35

Regenerate documentation Rd file. 

Update NEWS

**Comment by spgarbet** [comment]
── R CMD check results ───────────────────────────────────── redcapAPI 2.9.1 ────
Duration: 32.6s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

**Comment by spgarbet** [comment]
```
Failure (test-204-exportTypedRecords-withRepeatingInstruments.R:88:5): Including system fields in 'fields' doesn't produce an error
all(REDCAP_SYSTEM_FIELDS %in% names(Rec)) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

Failure (test-204-exportTypedRecords-withRepeatingInstruments.R:107:5): Including system fields in 'fields' doesn't produce an error
names(Rec) not equal to c("redcap_event_name", "redcap_data_access_group").
Lengths differ: 1 is not 2

Failure (test-204-exportTypedRecords-withRepeatingInstruments.R:130:5): ID fields are included on all calls
names(Rec) not equal to `minimum_field`.
Lengths differ: 4 is not 5

Failure (test-204-exportTypedRecords-withRepeatingInstruments.R:137:5): ID fields are included on all calls
all(minimum_field %in% names(Rec)) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

Failure (test-204-exportTypedRecords-withRepeatingInstruments.R:145:5): ID fields are included on all calls
all(c(minimum_field, "text_test") %in% names(Rec)) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
─────────────────────────────────────────────────────────────────────────────────
✔ |         17 | Export Typed Records Offline Argument Validation                
✔ |         16 | Export Typed Records Offline Functionality                      
✔ |         42 | exportBulkRecords [27.2s]                                       
✔ |         17 | Export Typed Reports Argument Validation                        
✔ |      3   0 | Export Typed Report Functionality                               
✖ | 10       37 | recastRecords.R [1.4s]                                         
─────────────────────────────────────────────────────────────────────────────────
Failure (test-250-recastRecords.R:69:5): Handle numeric indexing appropriately
sort(unique(Recast$dropdown_test)) not equal to c(1, 2, 3).
'current' is not a factor

Failure (test-250-recastRecords.R:71:5): Handle numeric indexing appropriately
sort(unique(Recast$checkbox_test___x)) not equal to c(0, 1).
'current' is not a factor

Failure (test-250-recastRecords.R:72:5): Handle numeric indexing appropriately
levels(Recast$checkbox_test___y) not equal to levels(Records$checkbox_test___y).
target is NULL, current is character

Failure (test-250-recastRecords.R:75:5): Handle numeric indexing appropriately
is.logical(Recast$truefalse_test) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

Error (test-250-recastRecords.R:77:5): Handle numeric indexing appropriately
Error in `devtools::test()`: 1 assertions failed:
 * Columns {12} requested in a data frame with 11 columns
Backtrace:
    ▆
 1. └─redcapAPI::recastRecords(...) at test-250-recastRecords.R:77:5
 2.   └─checkmate::reportAssertions(coll) at redcapAPI/R/fieldCastingFunctions.R:180:3

Failure (test-250-recastRecords.R:116:5): Handle logical indexing appropriately
sort(unique(Recast$dropdown_test)) not equal to c(1, 2, 3).
'current' is not a factor

Failure (test-250-recastRecords.R:118:5): Handle logical indexing appropriately
sort(unique(Recast$checkbox_test___x)) not equal to c(0, 1).
'current' is not a factor

Failure (test-250-recastRecords.R:119:5): Handle logical indexing appropriately
levels(Recast$checkbox_test___y) not equal to levels(Records$checkbox_test___y).
target is NULL, current is character

Failure (test-250-recastRecords.R:122:5): Handle logical indexing appropriately
is.logical(Recast$truefalse_test) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

Error (test-250-recastRecords.R:126:5): Handle logical indexing appropriately
Error in `devtools::test()`: 1 assertions failed:
 * 'fields' (logical) should be of length 11 and is length 12
Backtrace:
    ▆
 1. └─redcapAPI::recastRecords(...) at test-250-recastRecords.R:126:5
 2.   └─checkmate::reportAssertions(coll) at redcapAPI/R/fieldCastingFunctions.R:180:3
─────────────────────────────────────────────────────────────────────────────────
Maximum number of failures exceeded; quitting at end of file.
ℹ Increase this number with (e.g.) testthat::set_max_fails(Inf) 

══ Results ══════════════════════════════════════════════════════════════════════
Duration: 460.8 s

── Skipped tests (12) ───────────────────────────────────────────────────────────
• No value provided for EXPORT_REPORTS_ID. Tests Skipped (3):
  test-240-exportTypedReports-Functionality.R:8:5,
  test-240-exportTypedReports-Functionality.R:54:5,
  test-240-exportTypedReports-Functionality.R:72:5
• Tests to be developed for 3.0.0 release (9):
  test-151-exportRecords-ArgumentValidation.R:6:5,
  test-151-exportRecords-Functionality.R:6:5,
  test-152-exportRecordsWithDags.R:6:5, test-153-exportRecordsWithEvents.R:6:5,
  test-155-exportRecordsWithRepeatingInstruments.R:6:5,
  test-180-exportRecordsOffline-ArgumentValidation.R:6:5,
  test-180-exportRecordsOffline-Functionality.R:6:5,
  test-190-exportReports-ArgumentValidation.R:6:5,
  test-190-exportReports-Functionality.R:6:5

── Failed tests ─────────────────────────────────────────────────────────────────
Failure (test-204-exportTypedRecords-withRepeatingInstruments.R:88:5): Including system fields in 'fields' doesn't produce an error
all(REDCAP_SYSTEM_FIELDS %in% names(Rec)) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

Failure (test-204-exportTypedRecords-withRepeatingInstruments.R:107:5): Including system fields in 'fields' doesn't produce an error
names(Rec) not equal to c("redcap_event_name", "redcap_data_access_group").
Lengths differ: 1 is not 2

Failure (test-204-exportTypedRecords-withRepeatingInstruments.R:130:5): ID fields are included on all calls
names(Rec) not equal to `minimum_field`.
Lengths differ: 4 is not 5

Failure (test-204-exportTypedRecords-withRepeatingInstruments.R:137:5): ID fields are included on all calls
all(minimum_field %in% names(Rec)) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

Failure (test-204-exportTypedRecords-withRepeatingInstruments.R:145:5): ID fields are included on all calls
all(c(minimum_field, "text_test") %in% names(Rec)) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

Failure (test-250-recastRecords.R:69:5): Handle numeric indexing appropriately
sort(unique(Recast$dropdown_test)) not equal to c(1, 2, 3).
'current' is not a factor

Failure (test-250-recastRecords.R:71:5): Handle numeric indexing appropriately
sort(unique(Recast$checkbox_test___x)) not equal to c(0, 1).
'current' is not a factor

Failure (test-250-recastRecords.R:72:5): Handle numeric indexing appropriately
levels(Recast$checkbox_test___y) not equal to levels(Records$checkbox_test___y).
target is NULL, current is character

Failure (test-250-recastRecords.R:75:5): Handle numeric indexing appropriately
is.logical(Recast$truefalse_test) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

Error (test-250-recastRecords.R:77:5): Handle numeric indexing appropriately
Error in `devtools::test()`: 1 assertions failed:
 * Columns {12} requested in a data frame with 11 columns
Backtrace:
    ▆
 1. └─redcapAPI::recastRecords(...) at test-250-recastRecords.R:77:5
 2.   └─checkmate::reportAssertions(coll) at redcapAPI/R/fieldCastingFunctions.R:180:3

Failure (test-250-recastRecords.R:116:5): Handle logical indexing appropriately
sort(unique(Recast$dropdown_test)) not equal to c(1, 2, 3).
'current' is not a factor

Failure (test-250-recastRecords.R:118:5): Handle logical indexing appropriately
sort(unique(Recast$checkbox_test___x)) not equal to c(0, 1).
'current' is not a factor

Failure (test-250-recastRecords.R:119:5): Handle logical indexing appropriately
levels(Recast$checkbox_test___y) not equal to levels(Records$checkbox_test___y).
target is NULL, current is character

Failure (test-250-recastRecords.R:122:5): Handle logical indexing appropriately
is.logical(Recast$truefalse_test) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

Error (test-250-recastRecords.R:126:5): Handle logical indexing appropriately
Error in `devtools::test()`: 1 assertions failed:
 * 'fields' (logical) should be of length 11 and is length 12
Backtrace:
    ▆
 1. └─redcapAPI::recastRecords(...) at test-250-recastRecords.R:126:5
 2.   └─checkmate::reportAssertions(coll) at redcapAPI/R/fieldCastingFunctions.R:180:3

[ FAIL 15 | WARN 0 | SKIP 12 | PASS 1194 ]
```

**Comment by spgarbet** [comment]
The 204 tests appear to just be exposing the change in expected behavior. These are easily fixed. The 250 are a bit more baffling.

**Comment by spgarbet** [comment]
I fixed 204 as much as I could. The remaining failing test is exposing a bug in how the dag logic is handled and the code needs fixed.

```

── Failure ('test-204-exportTypedRecords-withRepeatingInstruments.R:108:5'): Including system fields in 'fields' doesn't produce an error ──
names(Rec) not equal to c("redcap_event_name", "redcap_data_access_group").
Lengths differ: 1 is not 2

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 10 ]
```

**Comment by obregos** [comment]
════════════════════
Duration: 627.3 s

── Skipped tests  ─────
• No value provided for EXPORT_REPORTS_ID. Tests Skipped (3)
• Tests to be developed for 3.0.0 release (9)

[ FAIL 0 | WARN 0 | SKIP 12 | PASS 2131 ]

**Comment by spgarbet** [comment]
```
══ Results ═════════════════════════════════════════════════
Duration: 595.9 s

── Skipped tests (12) ──────────────────────────────────────
• No value provided for EXPORT_REPORTS_ID. Tests Skipped
  (3): test-240-exportTypedReports-Functionality.R:8:5,
  test-240-exportTypedReports-Functionality.R:54:5,
  test-240-exportTypedReports-Functionality.R:72:5
• Tests to be developed for 3.0.0 release (9):
  test-151-exportRecords-ArgumentValidation.R:6:5,
  test-151-exportRecords-Functionality.R:6:5,
  test-152-exportRecordsWithDags.R:6:5,
  test-153-exportRecordsWithEvents.R:6:5,
  test-155-exportRecordsWithRepeatingInstruments.R:6:5,
  test-180-exportRecordsOffline-ArgumentValidation.R:6:5,
  test-180-exportRecordsOffline-Functionality.R:6:5,
  test-190-exportReports-ArgumentValidation.R:6:5,
  test-190-exportReports-Functionality.R:6:5

[ FAIL 0 | WARN 0 | SKIP 12 | PASS 2131 ]
```

**Comment by spgarbet** [comment]
I don't know why mine is skipping the report tests, but that's unrelated. Otherwise, looks like we're there.

**Review by spgarbet — APPROVED** [review]

**Pull request merged**
