### PR TITLE
exportBulkRecords default on forms argument #157

### PR DESCRIPTION
**Pull request by spgarbet**
Highlight these lines: https://github.com/vubiostat/redcapAPI/compare/main...issue-157-forms-arg#diff-bac810a5d512fa74055da250554b7353126d160ad9e2a1d8237408ea34428950R1000-R1005

The NA possible specification made the interface a bit difficult to detect user errors via checkmate. I think this denotes the complexity of dependent typing with constraints. It brings up the question, "should we have this as the interface design", specifically the allowed override via NA.

### CODE REVIEW

**Comment by spgarbet** [comment]
Maybe I should rework, such that before the check there's a

```
forms[is.na(forms)] <- NA_character_ 
```

before the `checkmate` validation. Then it's a lot simpler.

**Comment by nutterb** [comment]
I agree this is a tough one to validate. I'm not super happy with this.  How would you feel about two rounds of checks:

```
checkmate::assert_list(     x       = forms,   # First, just verify that it is actually a list that was passed. 
                            names = "named",
                            null.ok = TRUE,
                            add     = coll)

{pseudo note---remaining checks for envir, sep, and post}

checkmate::reportAssertions(coll)  # Return any findings

# Now we know forms is either NULL or a list, so do a second round of validations

if(!is.null(forms))
{
  forms[is.na(forms)] <- NA_character_ 
  
  checkmate::assert_subset( x       = names(forms),
                            choices = names(rcon),
                            add     = coll)
  
  checkmate::assert_list( x       = forms,
                          types   = c("character"),
                          add     = coll)
}

checkmate::reportAssertions(coll)
```

**Comment by spgarbet** [comment]
Agreed. Made those changes.

**Review by nutterb — APPROVED** [review]
I like it.  All tests pass. Check passes

**Pull request merged**
