### PR TITLE
Loosen import meta data val 381

### PR DESCRIPTION
**Pull request by spgarbet**
Fixing importMetaData validations.

### CODE REVIEW

**Comment by spgarbet** [comment]
─ R CMD check results  redcapAPI 2─
Duration: 38s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

**Comment by obregos** [comment]
All the tests pass, except I am getting errors for the logging tests again.

```
── Failure: Logs can be batched and match unbatched ────────────────────────────
BatchedLog$action not equal to SameLog$action.
Modes: logical, character
target is logical, current is character

── Failure: Logs can be batched and match unbatched ────────────────────────────
BatchedLog$username not equal to SameLog$username.
Modes: logical, character
target is logical, current is character

── Failure: Logs can be batched and match unbatched ────────────────────────────
BatchedLog$details not equal to SameLog$details.
Modes: logical, character
target is logical, current is character

── Failure: Logs can be batched and match unbatched ────────────────────────────
BatchedLog$record not equal to SameLog$record.
Modes: logical, character
target is logical, current is character
```

The BatchedLog record, username, details and action are all type logical and the fields for SameLog are character.

```
> BatchedLog$record
logical(0)
> SameLog$record
character(0)
```

**Comment by spgarbet** [comment]
This is a false positive. You have no logs in this project at this point in the past. I will need to add some logic to skip the test in this case.

**Comment by spgarbet** [comment]
Fixed issue with the tests.

**Review by obregos — APPROVED** [review]
[ FAIL 0 | WARN 0 | SKIP 12 | PASS 2061 ]

**Pull request merged**
