### PR TITLE
Previous patch missed some cases, #290 #297 #314

### PR DESCRIPTION
**Pull request by spgarbet**
Missed some cases. There is one thing to consider on this, the drop_utf8 flag is probably no longer needed. Should I just strip that out?

### CODE REVIEW

**Comment by spgarbet** [comment]
[ FAIL 0 | WARN 0 | SKIP 12 | PASS 2127 ]

**Comment by spgarbet** [comment]
── R CMD check results ─────────── redcapAPI 2.8.4 ────
Duration: 51.1s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

**Review by couthcommander — APPROVED** [review]
argument "drop_utf8" might be needed in future, but is unnecessary with these changes

**Comment by nutterb** [comment]
`drop_utf8` should probably go.  It used to invoke `cleanseMetaData`, which was a very heavy handed approach to trying to deal with this issue (and I don't think it worked anyway).  `exportMetaData` no longer uses `cleanseMetaData` and I deleted it in the 3.0.0 code.

**Pull request merged**
