### PR TITLE
Issue 35 Invalid Records report on export

### PR DESCRIPTION
**Pull request by spgarbet**
Quick working version of invalid records reporting. Be good to include in 2.7.0

### CODE REVIEW

**Comment by spgarbet** [comment]
@nutterb Please review.

**Comment by nutterb** [comment]
Something seems a little off. The .txt is actually an RMD file.  The result shows the field types being jumbled.

[invalid-test.txt](https://github.com/vubiostat/redcapAPI/files/11193562/invalid-test.txt)

image

I made changed the `exportVersion` call to rcon$version() and added two spaces to the end of a couple of lines so they would render new lines in markdown.

**Comment by spgarbet** [comment]
These changes look good.

**Review by nutterb — APPROVED** [review]
This looks good now.

**Pull request merged**
