### PR TITLE
Issue 26

### PR DESCRIPTION
**Pull request by spgarbet**
I don't know how to write a test with a library load / unload for this, but it needs to probably get pushed before the rework in Issue #10

### CODE REVIEW

**Comment by nutterb** [comment]
To unload a package, use `detach("package:Hmisc", unload = TRUE)`

**Review by nutterb — COMMENTED** [review]
## Critical recommendations
1. Line 186: This should be `for (i in seq_len(nrow(checkbox_meta)))`; seq always starts at one, so seq(0) returns c(1, 0). Should this code ever be hit where there are zero rows in checkbox_meta, it will fail. Using seq_len will make it simply skip the loop. 
2. Line 191: I recommend `recordnames[grepl(sprintf("^%s", checkbox_fieldname), recordnames)]`. This will force the match to begin at the start of the field name. (prereq_checkbox and no_prereq_checkbox are both being caught in your pattern)
3. I'm unsure of the intent for the `fname` variable. For a variable titled `prereq_checkbox`, fname becomes "prereq_", and is then applied as the new variable name. I suspect the better value to use in lines 199 and 201 is checkbox_fieldname

## Cosmetic recommendations
1. Line 189: I recommend `checkbox_fieldname <- checkbox_meta$field_name[i]`. It's one less dimension of indexing and a bit more efficient (measured in microseconds, so not really a big deal)
2. Lines 192 - 193: the fieldChoiceMapping function is available in #38 . If adopted, these two lines could become `levels <- fieldChoiceMapping(checkbox_meta$select_choices_or_calculations[i])[, 2]
3. line 201 can be `records[[fname]] <- z`. This utilizes list indexing, which is slightly more efficient than data frame indexing.
4. If mchoice = TRUE and Hmisc is not installed, would it be worthwhile to issue a warning that Hmisc must be installed to utilize this option? As it stands now, I think this would just be skipped with no indication to the user why they weren't given the output they requested.

**Comment by spgarbet** [comment]
I'll get these changes made. Thanks for the critical review.

**Comment by spgarbet** [comment]
The test cases showed some breakage from these changes. I misunderstood checking for installed packages and instead were loading it if it existed. The changes request broke the code somehow. I'm going to add test cases for Hmisc now, it's too important.  :)

**Comment by nutterb** [comment]
Two more things I noticed while I was kicking the tires on this

**first**
https://github.com/vubiostat/redcapAPI/pull/37/files#diff-d03833c31c06986c737d55780671d40e3d48a7e670789fced3f1ceb446d2d62bR216

you have `checked <- records[,fields] != 'Checked'`. If a user were to use `labels = FALSE`, the checkbox variables would be left with the 0/1 coding. After establishing the value of `mchoice` at the start of fieldToVar, you may want to create a `records_raw <- records` and then use `checked <- records_raw[,fields] != '1'`. (redcapAPI always pulls the raw codings)

**second**
https://github.com/vubiostat/redcapAPI/pull/37/files#diff-d03833c31c06986c737d55780671d40e3d48a7e670789fced3f1ceb446d2d62bR215

`opts <- as.data.frame(matrix(rep(seq_along(fields), nrow(records)), nrow=nrow(records), byrow=TRUE))`

This is always going to create options of 1, 2, 3, 4.  But something like prereq_checkbox has options coded 1, 2, abc, 4.  Beyond that, my reading in the mChoice documentation makes me think the labels would be preferred over the codes.  So maybe something like this?

`opts <- as.data.frame(matrix(rep(levels, nrow(records)), nrow=nrow(records), byrow=TRUE))`

And if you want to have this respect the user's choice of `labels = TRUE`, online 213, you could define `levels <- sapply(opts, function(x) x[1 + labels])`

**Comment by spgarbet** [comment]
First, I can fix this. Just got the last round of changes working. I'll write a test case for this.

Second, this is intentional. It's how mChoice works.

**Comment by spgarbet** [comment]
This is ready for review to merge again.

**Review by nutterb — APPROVED** [review]
This work accomplishes the goal. Tests are passing and appear to be sufficient to the use cases for which these additions are intended. 

The only observations I have are that the arguments defaults `labels = NULL` and `mchoice = NULL` might come back to haunt us later.  Especially the `labels` argument. When I force this to remain NULL, the mchoice content I get back takes the appearance of "character(0);character(0);character(0)". _However_, the value of the argument is so well controlled in the current implementation that this cannot become a problem unless someone were to make a new implementation that didn't explicitly pass the labels argument. 

Whereas this is robust enough to function and there appears to be a strong desire to have it available, I recommend pushing this out and making it available to users. If there is a desire to change the default values of labels (probably to `TRUE`) and mchoice (I would recommend `logical(0)`), we can open another issue and quietly make those adjustments without interfering with user work.

**Pull request merged**
