### PR TITLE
Delete records 9

### PR DESCRIPTION
**Pull request by spgarbet**
I think delete records is finished. This is working and the tests are passing. Issue #9

### CODE REVIEW

**Comment by spgarbet** [comment]
@nutterb  or @obregos  would you review and we can push this over to the main branch?

**Review by obregos — APPROVED** [review]
All test cases passing.

**Comment by obregos** [comment]
All test cases passing. Submitted approved review.

Savannah Obregon | Application Developer
***@***.*** | Vanderbilt University Medical Center
________________________________

**Comment by spgarbet** [comment]
This closes issue #9

**Pull request merged**
