### PR TITLE
104 purge restore

### PR DESCRIPTION
**Pull request by nutterb**
DANGER!! The test suite incorporates the ability to purge and restore project structures. If you run the test suite against the normal API_KEY in `tests/testthat/helper-REDCapQACredentials.R`, the TestRedcapApi project will undergo a lot of changes. (Once the tests all pass, the project should end up where it started, but you should be aware that it's going to happen)

### Major Changes

1. Adds `preserveProject`, which accumulates all of the project records and structural data into a list that can be used to restore a project. (caveat: it does not preserve files nor the file repository)
2. Adds `purgeProject`, which can delete all records and/or structural data. Alternately, it can purge only selected elements. Highly destructive.
3. Adds `restoreProject`, which can perfrom multiple import actions to insert records and/or project structure. When given a list--such as the one created by `preserveProject`--it will restore the project to the status of the values in the list. 

These changes make it possible to perform testing on projects of varying complexity and structure while being able to restore the original state rather easily. The test suite makes use of these purge and restore projects in earlier tests that explore structural changes. 

Most tests are still performed using the TestingRedcapApi project structure that currently exists. 

### Minor Changes

* Several changes to structural import/export methods where bugs were exposed due to increased exposure to different project structures.
* exportFiles/importFiles are more robust when working with repeating instruments
* exportRecordsTyped returns `data.frame()` if there are no records in the project.
* validateImport_methods gainst the ability to recognize datetime_hm type fields.
* All but two tests that had been skipped are now run. Several new tests added

### CODE REVIEW

**Comment by spgarbet** [comment]
OMG. The mythical rebuild from scratch exists! This looks like a lot of work. Will review tomorrow.

**Comment by spgarbet** [comment]
API_KEY is commented out in the test helper-REDCapQACredentials.R

Test failure:

**Comment by nutterb** [comment]
Ok, I was trying a little too hard not to blow up the test project unexpectedly. Oops

**Comment by spgarbet** [comment]
What about the failing test?

**Comment by nutterb** [comment]
Sorry, the details of the error didn't show up in my e-mail, and I missed important context. 

I had not exactly matched the file repository structure. I've adapted the tests to the test project file repository.

**Review by spgarbet — APPROVED** [review]
Looks good.

**Pull request merged**
