### PR TITLE
Address converting vectors to API arrays, fieldChoiceMapping, remove dependencies

### PR DESCRIPTION
**Pull request by nutterb**
This request addresses Issues 

* #33 (parsing vectors to API parameters)
* #29 (remove stringr dependency). The work here also includes the function fieldChoiceMapping. This might be relevant to https://github.com/vubiostat/redcapAPI/pull/37/files#diff-d03833c31c06986c737d55780671d40e3d48a7e670789fced3f1ceb446d2d62bR192 which parses the field choices for a checkbox. 
* #32 (removes version argument from checkbox_suffix; this benefitted from fieldChoiceMapping, so I worked them in the same branch)
* #31 (fixes export users)
* #30 (fixing export users happened to remove this dependency)

Tests are updated. The only two that are skipped are related to DAGs. I'm not very experienced with setting those up, and am not sure if it's possible to do in a test database. I wrote the tests as placeholders so that we could think about them. I'm also okay with removing them if it isn't something you're interested in dealing with at the moment.

### CODE REVIEW

**Comment by spgarbet** [comment]
I get the following test failures:

Error (test-exportUsers.R:75:5): Returns a data frame when called with defaults
Error in `unique(rcon$metadata()$form_name)`: object 'rcon' not found
Backtrace:
 1. redcapAPI::exportUsers(rcon)
      at test-exportUsers.R:75:4
 2. redcapAPI:::exportUsers.redcapApiConnection(rcon)
      at redcapAPI/R/exportUsers.R:78:15
 3. redcapAPI:::.exportUsers_separateFormAccess(...)
      at redcapAPI/R/exportUsers.R:183:4
 4. base::unique(rcon$metadata()$form_name)
      at redcapAPI/R/exportUsers.R:214:2

Error (test-exportUsers.R:84:5): Returns a data frame with dates = FALSE
Error in `unique(rcon$metadata()$form_name)`: object 'rcon' not found
Backtrace:
 1. checkmate::expect_data_frame(exportUsers(rcon, dates = FALSE))
      at test-exportUsers.R:84:4
 6. redcapAPI:::exportUsers.redcapApiConnection(rcon, dates = FALSE)
      at redcapAPI/R/exportUsers.R:78:15
 7. redcapAPI:::.exportUsers_separateFormAccess(...)
      at redcapAPI/R/exportUsers.R:183:4
 8. base::unique(rcon$metadata()$form_name)
      at redcapAPI/R/exportUsers.R:214:2

Error (test-exportUsers.R:92:5): Returns a data frame with labels = FALSE
Error in `unique(rcon$metadata()$form_name)`: object 'rcon' not found
Backtrace:
 1. checkmate::expect_data_frame(exportUsers(rcon, labels = FALSE))
      at test-exportUsers.R:92:4
 6. redcapAPI:::exportUsers.redcapApiConnection(rcon, labels = FALSE)
      at redcapAPI/R/exportUsers.R:78:15
 7. redcapAPI:::.exportUsers_separateFormAccess(...)
      at redcapAPI/R/exportUsers.R:183:4
 8. base::unique(rcon$metadata()$form_name)
      at redcapAPI/R/exportUsers.R:214:2
───────────────────────────────────────────────────────────────────────────────────────
✔ |         3 | exportVersion.R [0.3s]                                                 
✔ |        11 | fieldChoiceMapping.R [0.3s]                                            
✔ |        60 | fieldToVar [1.9s]                                                      
✔ |         7 | missingSummary [1.5s]                                                  
✔ |         3 | parseBranchingLogic                                                    
✖ | 1      32 | redcapConnection [4.1s]                                                
───────────────────────────────────────────────────────────────────────────────────────
Error (test-redcapConnection.R:113:5): caching of users
Error in `unique(rcon$metadata()$form_name)`: object 'rcon' not found
Backtrace:
 1. rcon$users()
      at test-redcapConnection.R:113:4
 2. redcapAPI (local) getter("user")
      at redcapAPI/R/redcapConnection.R:154:26
 4. redcapAPI:::exportUsers.redcapApiConnection(rc)
      at redcapAPI/R/exportUsers.R:78:15
 5. redcapAPI:::.exportUsers_separateFormAccess(...)
      at redcapAPI/R/exportUsers.R:183:4
 6. base::unique(rcon$metadata()$form_name)
      at redcapAPI/R/exportUsers.R:214:2
───────────────────────────────────────────────────────────────────────────────────────
✔ |        78 | validateteImport_methods [0.2s]                                        
✔ |         5 | vectorToApiBodyList.R                                                  

══ Results ════════════════════════════════════════════════════════════════════════════
Duration: 34.7 s

── Skipped tests  ─────────────────────────────────────────────────────────────────────
• At the time of writing, DAGs aren't set up in the test project. This test is skipped (2)

[ FAIL 4 | WARN 0 | SKIP 2 | PASS 310 ]

**Comment by spgarbet** [comment]
checking Rd \usage sections ... WARNING
  Documented arguments not in \usage in documentation object 'checkbox_suffixes':
    ‘version’
  
  Undocumented arguments in documentation object 'fieldChoiceMapping'
    ‘object’ ‘...’
  Documented arguments not in \usage in documentation object 'fieldChoiceMapping':
    ‘field_choice’
  
  Undocumented arguments in documentation object 'redcapConnection'
    ‘x’ ‘...’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

**Comment by nutterb** [comment]
Fixed exportUsers and corrected the documentation issues. I'm now getting all tests passed (except for two skipped) and a clean check.

**Comment by spgarbet** [comment]
I see the tests passing now. Check is clean as well.

**Review by spgarbet — APPROVED** [review]
This all looks good. This is a huge set of changes.

**Pull request merged**
