### PR TITLE
Domain url 353

### PR DESCRIPTION
**Pull request by spgarbet**
This doesn't pass check. Submitted refresh issue as separate PR.

### CODE REVIEW

**Comment by spgarbet** [comment]
Pay particular attention to the janky method of creating an updateable url on the connection object.

**Comment by couthcommander** [comment]
I would suggest using `unlockREDCap` to deal with updating the "url" for redirects. The connection test should be the point of failure. Users that don't use this will just get warnings/messages.

**Comment by spgarbet** [comment]
I'll rework with that target in mind.

**Comment by spgarbet** [comment]
@couthcommander changed as recommended.

**Comment by spgarbet** [comment]
@obregos can you run the test suite on this and also R CMD Check.

**Comment by spgarbet** [comment]
Well this is embarrassing, the test cases missed that I removed the redirect from makeApiCall.

**Comment by obregos** [comment]
══ Results 
Duration: 423.1 s

── Skipped tests  
• Tests to be developed for 3.0.0 release (9)

[ FAIL 0 | WARN 0 | SKIP 9 | PASS 2126 ]

**Review by couthcommander — APPROVED** [review]
I like this approach

**Pull request merged**
