### PR TITLE
156 prep user import

### PR DESCRIPTION
**Pull request by nutterb**
* removes extraneous information from the exportUsers data. 
* Adds `prepUserImportData`, which recasts human-readable data into the format expected by the importUsers API method
* Includes tests

Note: the new `prepUserImportData` should be of interest to #144 

EDIT: I wrote `importRecords` where I should have written `importUsers`.

### CODE REVIEW

**Comment by spgarbet** [comment]
I have questions reading over this trying to understand. Why isn't this automatic when calling importRecords? What would be a typical use case to add to the vignette to understand it better?

**Comment by nutterb** [comment]
My apologies.  I should have written `importUsers` instead of `importRecords`. I've edited the first posting.

I would think this would be embedded within `importUsers`, but that hasn't been written yet. Should I move that function into a branch for #144?  (I'm not at my cognitive best lately, so don't be afraid to tell redirect me0

**Comment by spgarbet** [comment]
Ah. Bingo `prepUserImportData`. I understand it all now. It's in the name!

**Comment by spgarbet** [comment]
Getting the following on CHECK: 

```
checking R code for possible problems ... NOTE
  prepUserImportData_validateAllFormsPresent: no visible binding for
    global variable ‘data’
  Undefined global functions or variables:
    data
  Consider adding
    importFrom("utils", "data")
  to your NAMESPACE file.
```

**Comment by spgarbet** [comment]
https://github.com/nutterb/redcapAPI/blob/156-prep-user-import/R/prepUserImportData.R#L191-L192

**Comment by nutterb** [comment]
Corrected for the no global warning variable.

**Comment by spgarbet** [comment]
── R CMD check results ───────────────────────────── redcapAPI 2.7.4 ────
Duration: 18.3s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

**Review by spgarbet — APPROVED** [review]

**Pull request merged**
